[project]
name = "snake-game"
version = "0.1.0"
description = "Classic Snake Game"
authors = [
    {name = "Khaldoon Sinjab", email = "sinjab@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pygame >=2.5.2,<3.0.0"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
